tasks:
  - name: Clone and install Neovim 
    command: cd /tmp; wget https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb; sudo apt-get install ./nvim-linux64.deb
  - name: Install Lunar Vim
    command: LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
  - name: Add Lunar Vim to path.
    command: echo "alias lvim='/home/gitpod/.local/bin/lvim'"
  - name: Start Lvim
    command: lvim